<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Debloat.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\*.json" LogicalName="Debloat.Data.%(Filename)%(Extension)" />
    <EmbeddedResource Include="Scripts\*" LogicalName="Debloat.Scripts.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Debloat.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\unattend-generator\UnattendGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>

</Project>
